# Introduction

# Metrics

# Our Process

First, we need to import pandas, geopandas, and our datasets: Arrest Data and Census Data.

In [8]:
import pandas as pd
import geopandas
arrest_data = pd.read_csv("arrest-data.csv")
census_data = pd.read_excel("census-data.xlsx")

ModuleNotFoundError: No module named 'geopandas'

We should sample our datasets to see what we're working with:

In [5]:
arrest_data.sample(3)

,PK,CCR,AGE,GENDER,RACE,ARRESTTIME,ARRESTLOCATION,OFFENSES,INCIDENTLOCATION,INCIDENTNEIGHBORHOOD,INCIDENTZONE,INCIDENTTRACT,COUNCIL_DISTRICT,PUBLIC_WORKS_DIVISION,X,Y
40824,2027035,20092447,35.0,F,W,2020-05-18T20:44:00,"2800 Block Wadlow ST Pittsburgh, PA 15212",2702 Aggravated Assault. / 2701(a)(3) Simple A...,"2800 Block Wadlow ST Pittsburgh, PA 15212",Marshall-Shadeland,1,2715.0,1.0,1.0,-80.028494,40.470155
45098,2032753,20216106,51.0,M,B,2020-11-20T09:40:00,"400 Block Heldman ST Pittsburgh, PA 15219",2701 Simple Assault. / 3304(a)(5) CRIMINAL MIS...,"400 Block Heldman ST Pittsburgh, PA 15219",Crawford-Roberts,2,305.0,6.0,3.0,-79.982024,40.441826
44852,2032377,20203918,52.0,F,W,2020-10-31T20:12:00,"1100 Block Spring Garden AV Pittsburgh, PA 15212",13(a)(16) Possession of Controlled Substance /...,"1100 Block Spring Garden AV Pittsburgh, PA 15212",Spring Garden,1,2412.0,1.0,1.0,-79.993344,40.459805

In [6]:
census_data.sample(3)

,Neighborhood,Sector #,Pop. 1940,Pop. 1950,Pop. 1960,Pop. 1970,Pop. 1980,Pop. 1990,Pop. 2000,Pop. 2010,...,% Other (2010),% White (2010),% 2+ Races (2010),% Hispanic (of any race) (2010),% Pop. Age < 5 (2010),% Pop. Age 5-19 (2010),% Pop. Age 20-34 (2010),% Pop. Age 35-59 (2010),% Pop. Age 60-74 (2010),% Pop. Age > 75 (2010)
11,Bon Air,6,814,1330,1500,1428,1144,1006,889,808,...,0.000000,0.934406,0.0074,0.009,0.0362,0.1634,0.2017,0.2503,0.2275,0.1210
39,Highland Park,12,8960,10239,9805,9223,8032,7029,6749,6395,...,0.010946,0.665051,0.0266,0.029,0.0680,0.1177,0.2641,0.3864,0.1118,0.0519
38,Hazelwood,9,11571,12371,12757,9937,7968,6456,5334,4317,...,0.005791,0.543433,0.0252,0.020,0.0449,0.2010,0.1575,0.3580,0.1441,0.0945

Now, we define a function that takes in a list of crime types and a dictionary and adds every instance of each crime to the